image: alpine:latest

before_script: |
  apk update
  apk add npm
  npm install -g tiddlywiki

pages:
  stage: deploy
  script: |
    ./Build.sh
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
