name: Build and Deploy with TiddlyWiki

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  page_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        sudo apt update
        sudo apt install -y wget npm
        sudo npm install -g tiddlywiki
        ./Bootstrap.sh
        #./Build.sh
        #./DeployOld.sh

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
